print("Digite um número inteiro")
inteiro1 = int(input())
print("Digite outro número inteiro")
inteiro2 = int(input())
print("Digite um número real")
real1 = float(input())
print("A =",(2*inteiro1+inteiro2/2))
print("B =",(3*inteiro1+real1))
print("C =",(real1**3))